---
# very basic tasks to ensure pip and tower-cli is installed
- block:
    - name: Enable EPEL repo
      package:
        name: "{{ epel_release_rpm }}"
        state: present
      when: install_pip|bool
      become: true

    - name: Ensure python pip2 is installed
      package:
        name: python3-pip
        state: present
      when: install_pip|bool
      become: true

    - name: Ensure ansible-tower-cli is installed
      pip:
        name: ansible-tower-cli
        state: present
        extra_args: --user
        executable: /usr/bin/pip3
  always:
    - name: Disable EPEL repo
      yum:
        name: epel-release
        state: absent
      when: install_pip|bool
      become: true
