---
# Note: This playbook needs ansible-tower-cli installed and configured to run successfully.
- name: Playbook to configure ansible tower for ldap authentication
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Include vars from tower-configs directory
      include_vars:
        dir: ../tower-configs
        ignore_files: [tower-config.yml.template]
        extensions: ["json", "yaml", "yml"]
  roles:
    - { role: roles/tower-cli-installer}
    - { role: roles/tower-settings, when: tower_setting_params is defined}
