---
- name: Backup Ansible Tower - JSON backup - only metadata/objects
  hosts: localhost
  connection: local
  roles:
    - role: roles/tower-roles/tower-cli-installer
    - role: roles/tower-roles/tower-restore
      meta_backup: True
      backup_path: /mnt/backups
