name: ansible-lint
on:
  push:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  lint:
    name: ansible-lint
    runs-on: ubuntu-18.04

    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: ansible-lint
        uses: ansible/ansible-lint-action@v4.1.0.post0

      - name: Run ansible-lint
        run: find . -type f -name "*.yml" | xargs ansible-lint -v

